spring.application.name=api-gateway
server.port=8765

# Eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

# Gateway Routes
spring.cloud.gateway.routes[0].id=quiz-service
spring.cloud.gateway.routes[0].uri=lb://QUIZ-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/quiz/**

spring.cloud.gateway.routes[1].id=question-service
spring.cloud.gateway.routes[1].uri=lb://QUESTION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/question/**

# Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}

management.endpoints.web.exposure.include=health,info,metrics,prometheus