spring.application.name=notification-service
server.port=8085

spring.cloud.config.fail-fast=true

spring.cloud.config.retry.initial-interval=5000
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.max-interval=10000

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/quizdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
management.endpoints.web.exposure.include=health,info,metrics,prometheus