spring.application.name=notification-service
server.port=8085

# Clear out or disable config-server fetching if this is running locally independent
spring.cloud.config.enabled=false

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/quizdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Registry Discovery Routing
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

# RabbitMQ Event Queue Messaging
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}

# Gmail SMTP Target Pipeline
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# CRITICAL EXPLICIT MAIL SECURITY OVERRIDES:
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Turn on active terminal debug logs so you can see the explicit SMTP handshake
spring.mail.properties.mail.smtp.debug=true

# Distributed Tracing Core Stack
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
management.endpoints.web.exposure.include=health,info,metrics,prometheus