spring.application.name=question-service
server.port=5001

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/questiondb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

# Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}

management.endpoints.web.exposure.include=health,info,metrics,prometheus